# Generated by Django 3.2 on 2021-05-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user'),
        ('movies_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_genres', models.CharField(max_length=24, unique=True)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies_list.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorization.user')),
            ],
        ),
    ]
