# Generated by Django 3.2 on 2021-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0004_auto_20210502_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='favourite_genres',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
