# Generated by Django 3.2 on 2021-05-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0006_alter_collections_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collections',
            unique_together=set(),
        ),
    ]
