# Generated by Django 3.2 on 2021-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0007_alter_collections_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='favourite_genres',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='user',
        ),
        migrations.AddField(
            model_name='collections',
            name='description',
            field=models.CharField(default='NULL', max_length=240),
            preserve_default=False,
        ),
    ]
