# Generated by Django 3.2 on 2021-05-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0008_auto_20210502_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collections',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
