# Generated by Django 3.2 on 2021-05-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies_list', '0009_auto_20210503_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Movielist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=240)),
                ('title', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=240)),
                ('genres', models.CharField(max_length=240)),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_list.collections')),
            ],
        ),
    ]
