# Generated by Django 3.2 on 2021-05-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0010_collections_movielist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movielist',
        ),
    ]
