# Generated by Django 3.2 on 2021-05-03 09:28

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0011_delete_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='movies',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
