# Generated by Django 3.2 on 2021-05-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0012_collections_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='movies',
            field=models.TextField(blank=True, default=[], null=True),
        ),
    ]
