# Generated by Django 3.2 on 2021-05-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=31, unique=True)),
                ('lastname', models.CharField(max_length=31, unique=True)),
                ('username', models.CharField(max_length=240, unique=True)),
                ('password', models.CharField(max_length=240, unique=True)),
            ],
        ),
    ]
