# Generated by Django 3.2 on 2021-05-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_user_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
