# Generated by Django 3.2 on 2021-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240, unique=True)),
                ('password', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'unique_together': {('username', 'password')},
            },
        ),
    ]
