# Generated by Django 3.2 on 2021-05-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
